// Code generated by "stringer -type=NodeKind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ND_ADD-0]
	_ = x[ND_SUB-1]
	_ = x[ND_MUL-2]
	_ = x[ND_DIV-3]
	_ = x[ND_NEG-4]
	_ = x[ND_MOD-5]
	_ = x[ND_EQ-6]
	_ = x[ND_NE-7]
	_ = x[ND_LT-8]
	_ = x[ND_LE-9]
	_ = x[ND_ASSIGN-10]
	_ = x[ND_COMMA-11]
	_ = x[ND_MEMBER-12]
	_ = x[ND_ADDR-13]
	_ = x[ND_DEREF-14]
	_ = x[ND_NOT-15]
	_ = x[ND_BITNOT-16]
	_ = x[ND_RETURN-17]
	_ = x[ND_IF-18]
	_ = x[ND_FOR-19]
	_ = x[ND_BLOCK-20]
	_ = x[ND_FUNCALL-21]
	_ = x[ND_EXPR_STMT-22]
	_ = x[ND_STMT_EXPR-23]
	_ = x[ND_VAR-24]
	_ = x[ND_NUM-25]
	_ = x[ND_CAST-26]
}

const _NodeKind_name = "ND_ADDND_SUBND_MULND_DIVND_NEGND_MODND_EQND_NEND_LTND_LEND_ASSIGNND_COMMAND_MEMBERND_ADDRND_DEREFND_NOTND_BITNOTND_RETURNND_IFND_FORND_BLOCKND_FUNCALLND_EXPR_STMTND_STMT_EXPRND_VARND_NUMND_CAST"

var _NodeKind_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 41, 46, 51, 56, 65, 73, 82, 89, 97, 103, 112, 121, 126, 132, 140, 150, 162, 174, 180, 186, 193}

func (i NodeKind) String() string {
	if i < 0 || i >= NodeKind(len(_NodeKind_index)-1) {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[i]:_NodeKind_index[i+1]]
}
